dataset:
  root_dir: ipd_data/ipd
  cam_ids: [cam2]
  modality: [rgb, depth, aolp, dolp]
  split: val

training:
  batch_size: 1
  epochs: 1
  num_workers: 2
  device: cuda

optim:
  lr_rot: 1e-5
  lr_trans: 1e-4
  weight_decay: 0.0
