dataset:
  root_dir: ipd_data/ipd
  cam_ids: [cam2]
  modality: [rgb, depth]
  split: val

training:
  batch_size: 4
  epochs: 1
  num_workers: 4
  device: cuda

optim:
  lr_rot: 1e-3
  lr_trans: 1e-3
  weight_decay: 0.0
