dataset:
  remote_base_url: ipd_data/ipd
  cam_ids: [cam1, cam2]
  modality: [rgb, depth] #, aolp, dolp]
  train_split: train_pbr
  val_split: val
  model_split: models

training:
  batch_size: 4
  epochs: 1
  num_workers: 2
  device: cuda
  patience: 10
  encoder: fusenet #resnet
  freeze_candidates: false
  freeze_refiner: false

optim:
  lr: 1e-4
  weight_decay: 0.0

renderer:
  width: 640
  height: 480
  device: cuda
  render_weight: 1.0
